options("crayon.enabled" = FALSE)
options("max.print" = 3000) 
do.call(Sys.setenv, jsonlite::fromJSON(readLines("./bin/config.json")))
options(setWidthOnResize = TRUE)
LOWER_CUTOFF <- lubridate::ymd_hms("2021-08-11T00-00-00")
